In [1]:
import sqlite3
import dash
from dash import html as dhtml
from dash import dcc
import pandas as pd
import numpy as np
from dash.dependencies import Input, Output
from django_plotly_dash import DjangoDash
from pathlib import Path
from os.path import join as pjoin

In [3]:
BASE_DIR = Path("plotly_app.py").resolve().parent.parent

In [5]:
conn = sqlite3.connect("stats_db.sqlite3")

In [7]:
df_from_db = pd.read_sql_query("SELECT * FROM sdata", conn)

In [8]:
df_from_db

,Date,Name,Performance_Duration,Total_Distance,Walk_Distance,Jog_Distance,Run_Distance,Sprint_Distance,Sprint_Efforts,Zone_1_Distance,...,L1_aewma,L1_cewma,L2_aewma,L2_cewma,aEWMAspt,cEWMAspt,acwr_spt,acwr_l1,acwr_l2,ACWR_AVG
0,2022-08-02 00:00:00,Allie Larsen,85,3448.05,2092.40,1052.05,294.57,9.03,0,2092.40,...,862.01,237.80,21.48,5.92,42.51,11.73,3.62,3.62,3.63,3.62
1,2022-08-03 00:00:00,Allie Larsen,95,5639.85,2931.28,1837.14,801.16,70.26,4,2931.28,...,2056.47,610.36,84.48,24.37,104.63,30.99,3.38,3.37,3.47,3.41
2,2022-08-04 00:00:00,Allie Larsen,69,2787.90,1747.75,764.32,273.35,2.48,0,1747.75,...,2239.33,760.54,77.16,26.50,113.17,38.43,2.94,2.94,2.91,2.93
3,2022-08-05 00:00:00,Allie Larsen,90,3756.47,2384.64,1019.00,325.91,26.92,1,2384.64,...,2618.61,967.16,82.64,31.50,135.30,49.69,2.72,2.71,2.62,2.68
4,2022-08-06 00:00:00,Allie Larsen,0,0.00,0.00,0.00,0.00,0.00,0,0.00,...,1963.96,900.46,61.98,29.33,101.48,46.26,2.19,2.18,2.11,2.16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1711,2022-10-02 00:00:00,Sydney Haustein,175,10718.32,4029.82,3632.95,2933.08,122.47,5,4029.82,...,6118.01,4594.10,347.02,201.37,280.90,208.13,1.35,1.33,1.72,1.47
1712,2022-10-03 00:00:00,Sydney Haustein,0,0.00,0.00,0.00,0.00,0.00,0,0.00,...,4588.51,4277.27,260.26,187.48,210.68,193.78,1.09,1.07,1.39,1.18
1713,2022-10-04 00:00:00,Sydney Haustein,0,0.00,0.00,0.00,0.00,0.00,0,0.00,...,3441.38,3982.29,195.20,174.55,158.01,180.42,0.88,0.86,1.12,0.95
1714,2022-10-05 00:00:00,Sydney Haustein,102,3119.14,2126.29,751.31,236.37,5.17,0,2126.29,...,3360.82,3922.76,157.19,165.49,158.72,179.07,0.89,0.86,0.95,0.90
1715,2022-10-06 00:00:00,Sydney Haustein,0,0.00,0.00,0.00,0.00,0.00,0,0.00,...,2520.62,3652.22,117.89,154.08,119.04,166.72,0.71,0.69,0.77,0.72